server:
  port: 8082

spring:
  application:
    name: event-service
  config:
    import: optional:configserver:http://config-server:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/hackathon}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://postgres:5432/eventdb
    username: hackathon
    password: hackathon
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    enabled: false
