server:
  port: 8083

spring:
  application:
    name: team-service
  config:
    import: optional:configserver:http://config-server:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/hackathon}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/teamdb
    username: hackathon
    password: hackathon
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    enabled: false
