spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/submissiondb
    username: hackathon
    password: hackathon
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
